# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170918_1242'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Imagem'),
        ),
    ]
