# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_meterial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meterial',
            new_name='Material',
        ),
    ]
