# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
