# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171002_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nova Senha', 'verbose_name_plural': 'Novas Senhas'},
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='createad_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado?'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É da equipe?'),
        ),
    ]
